[tox]
envlist = clean, py312
; envlist = clean, check, docs, report
; skipsdist = true

[testenv]
deps =
    pytest
    pytest-cov
commands =
    pytest src/tests
    pytest --cov --cov-append --cov-report=term-missing


[coverage:report]
skip_empty = true


; If you are trying to create a single distribution with multiple packages
; on purpose, you should not rely on automatic discovery.
; Instead, consider the following options:

; 1. set up custom discovery (`find` directive with `include` or `exclude`)
; 2. use a `src-layout`
; 3. explicitly set `py_modules` or `packages` with a list of names

; To find more information, look for "package discovery" on setuptools docs.


; [testenv:docs]
; usedevelop = true
; deps =
;     -r{toxinidir}/docs/requirements.txt
; commands =
;     sphinx-build {posargs:-E} -b html docs dist/docs
;     sphinx-build -b linkcheck docs dist/docs

; [testenv:report]
; deps =
;     coverage
; skip_install = true
; commands =
;     coverage report
;     coverage html

[testenv:clean]
deps =
    coverage
skip_install = true
commands =
    coverage erase


; [tool.tox]
; requires = ["tox>=4.19"]
; env_list = ["3.13", "3.12", "3.11", "3.10", "lint", "type"]

; [tool.tox.env_run_base]
; description = "Run test under {base_python}"
; commands = [["pytest"]]

; [tool.tox.env.type]
; description = "run type check on code base"
; deps = ["mypy==1.11.2", "types-cachetools>=5.5.0.20240820", "types-chardet>=5.0.4.6"]
; commands = [["mypy", "src{/}tox"], ["mypy", "tests"]]
