[tox]
envlist = clean, testenv, py312
; envlist = clean, check, docs, report
; skipsdist = true

[testenv]
deps =
    poetry
commands_pre =
    poetry install
commands =
    poetry run pytest --maxfail=1 --cov=src/tests --cov-report=term-missing src/tests
; deps =
;     pytest
;     pytest-cov
; commands =
;     pytest src/tests
;     pytest --cov --cov-append --cov-report=term-missing


[coverage:report]
skip_empty = true

[testenv:lint]
description = Run Ruff Linter
deps = ruff
commands = ruff check src/firesat src/tests

[testenv:clean]
deps =
    coverage
skip_install = true
commands =
    coverage erase


; If you are trying to create a single distribution with multiple packages
; on purpose, you should not rely on automatic discovery.
; Instead, consider the following options:

; 1. set up custom discovery (`find` directive with `include` or `exclude`)
; 2. use a `src-layout`
; 3. explicitly set `py_modules` or `packages` with a list of names

; To find more information, look for "package discovery" on setuptools docs.


; [testenv:docs]
; usedevelop = true
; deps =
;     -r{toxinidir}/docs/requirements.txt
; commands =
;     sphinx-build {posargs:-E} -b html docs dist/docs
;     sphinx-build -b linkcheck docs dist/docs

; [testenv:report]
; deps =
;     coverage
; skip_install = true
; commands =
;     coverage report
;     coverage html
